Repository BrendanParmer/NodeToPython, pull requests merged in 2024-11, with the labels that each got.

#133 fix: node socket interface menu is now correctly handle
  NodeToPython/ntp_operator.py
Labels: bug

#135 Menu socket fixes
  CONTRIBUTORS.md
  NodeToPython/ntp_operator.py
Labels: bug, documentation

#136 Blender 4.3
  CONTRIBUTORS.md
  NodeToPython/__init__.py
  NodeToPython/blender_manifest.toml
  NodeToPython/compositor/operator.py
  NodeToPython/geometry/node_tree.py
  NodeToPython/geometry/operator.py
  NodeToPython/node_settings.py
  NodeToPython/ntp_operator.py
  NodeToPython/utils.py
  docs/README.md
  tools/node_settings_generator/parse_nodes.py
  tools/node_settings_generator/types_utils.py
Labels: enhancement

#137 v3.3
  NodeToPython/__init__.py
  NodeToPython/blender_manifest.toml
  NodeToPython/compositor/operator.py
  NodeToPython/geometry/node_tree.py
  NodeToPython/geometry/operator.py
  NodeToPython/node_settings.py
  NodeToPython/ntp_operator.py
  NodeToPython/options.py
  NodeToPython/shader/operator.py
  NodeToPython/utils.py
  tools/node_settings_generator/parse_nodes.py
  tools/node_settings_generator/types_utils.py
Labels: bug, enhancement, refactor
